name: Build & test Go
on: [push]
jobs: 
  test: 
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Format Checker
        run: test -z "$(gofmt -l .)"

      - name: Test Code
        run: go test -v -race -coverprofile="cov.out" -covermode=atomic ./...
        
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./cov.out
          